**Intro to Numpy**

**Uses**
1. Machine Learning
2. Data Science
3. Image and Signal Processing
4. Scientific computing
5. Quantum Computing

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


**Numpy Array Creation**


In [2]:
import numpy as np
list1 = [2,4,5,6,7]


In [3]:
arr1 = np.array(list1)
print(arr1)

[2 4 5 6 7]


In [4]:
arr1 = np.array([1,4,87,4])
print(arr1)

[ 1  4 87  4]


*Create an array with np.zeros()*

In [5]:
arr1 = np.zeros(4)
print(arr1)

[0. 0. 0. 0.]


*Create an array with np.arrange()*

In [6]:
arr = np.arange(5)

print(arr)

[0 1 2 3 4]


In [7]:
arr = np.arange(1,9,2)

print(arr)

[1 3 5 7]


*Create an array with np.random.rand()*

In [16]:
arr = np.random.rand(4)

print(arr)

[0.80557871 0.10160239 0.60232785 0.62894239]


** Create an 2-D array **

In [22]:
arr = np.array([[1,3,5],[6,3,7]])
# print(arr)
print(arr[1,1])

3


In [23]:
arr3 = np.array([[  [1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr3(1,2,2))

TypeError: 'numpy.ndarray' object is not callable

Dimensions

In [24]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
arr = np.zeros((2,3,5))
print(arr)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


Speciefic Value

In [31]:
arr = np.full((2,3),5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [38]:
arr = np.random.rand(2,3)
print(arr)
print()
arr = np.random.rand(2,3,2)
print(arr)

[[0.40570391 0.34277711 0.84768359]
 [0.0839891  0.70328114 0.01395077]]

[[[0.07062241 0.35014084]
  [0.3001709  0.66660594]
  [0.45495943 0.70163035]]

 [[0.07204298 0.3400307 ]
  [0.88042547 0.01957921]
  [0.90770007 0.31313568]]]


Data Types

In [48]:
int_arr= np.array([4,6,7],dtype='int64')
print(int_arr, int_arr.dtype)

float_arr= np.array([4.2,6.3,7.4])
print(float_arr)



[4 6 7] int64
[4.2 6.3 7.4]
